# Generated by Django 4.2.8 on 2026-09-17 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetasApp', '0002_receta_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='categoria',
            field=models.CharField(choices=[('pasteleria', 'Pastelería'), ('panaderia', 'Panadería'), ('almuerzos', 'Almuerzos'), ('postres', 'Postres'), ('otros', 'Otros')], default='otros', max_length=20),
        ),
    ]
