# Generated by Django 4.2.8 on 2026-09-18 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetasApp', '0003_receta_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='dificultad',
            field=models.CharField(blank=True, choices=[('facil', 'Fácil'), ('media', 'Media'), ('dificil', 'Difícil')], max_length=10),
        ),
        migrations.AddField(
            model_name='receta',
            name='favorito',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='receta',
            name='porciones',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receta',
            name='tiempo_preparacion',
            field=models.CharField(blank=True, help_text='Ej: 30 min', max_length=50),
        ),
    ]
