# Generated by Django 4.2.8 on 2026-09-18 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetasApp', '0004_receta_dificultad_receta_favorito_receta_porciones_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='valoracion_cantidad',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='receta',
            name='valoracion_suma',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
