# Generated by Django 4.2.8 on 2026-09-18 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recetasApp', '0005_receta_valoracion_cantidad_receta_valoracion_suma'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receta',
            name='valoracion_cantidad',
        ),
        migrations.RemoveField(
            model_name='receta',
            name='valoracion_suma',
        ),
        migrations.CreateModel(
            name='Valoracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('puntaje', models.PositiveIntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones', to='recetasApp.receta')),
            ],
            options={
                'unique_together': {('receta', 'nombre')},
            },
        ),
    ]
